# Generated by Django 4.0.6 on 2022-07-15 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileUser', '0004_alter_profilesettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledoctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilepatient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='profile',
            field=models.CharField(choices=[('', ''), ('Paciente', 'Paciente'), ('Médico', 'Médico')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
