# Generated by Django 4.0.6 on 2022-07-15 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileUser', '0005_alter_profiledoctor_user_alter_profilepatient_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledoctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profileDoctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilepatient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profilePatient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
